[package]
name = "nc-bookmark-sync"
version = "0.1.0"
authors = ["Stefan Boere <s.boere@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
